"""Init entire database schema

Revision ID: 8ba33be20321
Revises: 
Create Date: 2026-05-31 13:41:55.568151
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ba33be20321'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('tasks', sa.Integer(), nullable=False),
    sa.Column('intervals', sa.Integer(), nullable=False),
    sa.Column('hosts', sa.JSON(), nullable=True),
    sa.Column('calculated_pi', sa.Float(), nullable=False),
    sa.Column('error', sa.Float(), nullable=False),
    sa.Column('elapsed_time_seconds', sa.Float(), nullable=False),
    sa.Column('theoretical_amdahl_speedup', sa.Float(), nullable=False),
    sa.Column('theoretical_gustafson_speedup', sa.Float(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_nodes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_label', sa.String(length=255), nullable=True),
    sa.Column('hw_model', sa.String(length=100), nullable=True),
    sa.Column('camera_model', sa.String(length=100), nullable=True),
    sa.Column('ai_model_name', sa.String(length=100), nullable=True),
    sa.Column('ai_model_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_nodes_hostname'), 'sensor_nodes', ['hostname'], unique=False)
    op.create_index(op.f('ix_sensor_nodes_status'), 'sensor_nodes', ['status'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('detection_events',
    sa.Column('sensor_node_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('raw_detections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=150), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_node_id'], ['sensor_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_events_event_type'), 'detection_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_detection_events_sensor_node_id'), 'detection_events', ['sensor_node_id'], unique=False)
    op.create_index(op.f('ix_detection_events_severity'), 'detection_events', ['severity'], unique=False)
    op.create_table('health_statuses',
    sa.Column('sensor_node_id', sa.UUID(), nullable=False),
    sa.Column('cpu_usage_percent', sa.Float(), nullable=True),
    sa.Column('memory_usage_percent', sa.Float(), nullable=True),
    sa.Column('disk_usage_percent', sa.Float(), nullable=True),
    sa.Column('cpu_temperature_celsius', sa.Float(), nullable=True),
    sa.Column('gpu_temperature_celsius', sa.Float(), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.Column('network_status', sa.String(length=20), nullable=True),
    sa.Column('inference_fps', sa.Float(), nullable=True),
    sa.Column('extra_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_node_id'], ['sensor_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_statuses_sensor_node_id'), 'health_statuses', ['sensor_node_id'], unique=False)
    op.create_table('system_logs',
    sa.Column('sensor_node_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_node_id'], ['sensor_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_index(op.f('ix_system_logs_sensor_node_id'), 'system_logs', ['sensor_node_id'], unique=False)
    op.create_index(op.f('ix_system_logs_source'), 'system_logs', ['source'], unique=False)
    op.create_table('detection_images',
    sa.Column('detection_event_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('bucket', sa.String(length=100), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('image_type', sa.String(length=20), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['detection_event_id'], ['detection_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_detection_images_detection_event_id'), 'detection_images', ['detection_event_id'], unique=False)
    op.create_table('notifications',
    sa.Column('detection_event_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('notification_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['detection_event_id'], ['detection_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_detection_event_id'), 'notifications', ['detection_event_id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_detection_event_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_detection_images_detection_event_id'), table_name='detection_images')
    op.drop_table('detection_images')
    op.drop_index(op.f('ix_system_logs_source'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_sensor_node_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_health_statuses_sensor_node_id'), table_name='health_statuses')
    op.drop_table('health_statuses')
    op.drop_index(op.f('ix_detection_events_severity'), table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_sensor_node_id'), table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_event_type'), table_name='detection_events')
    op.drop_table('detection_events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sensor_nodes_status'), table_name='sensor_nodes')
    op.drop_index(op.f('ix_sensor_nodes_hostname'), table_name='sensor_nodes')
    op.drop_table('sensor_nodes')
    op.drop_table('cluster_runs')
    # ### end Alembic commands ###
